import "./globals.css";
import { AuthProvider } from "./lib/auth";
import { Bricolage_Grotesque } from "next/font/google";

const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${bricolage.className}`}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
